workers_dev = false

name = "english-verb-worker"
main = "src/index.js"
compatibility_date = "2024-11-01" # 建议使用较新的日期

# --- 核心修改：配置静态资源 ---
[assets]
directory = "./public"   # 告诉 Worker 你的 HTML 在 public 文件夹里
binding = "EN_VERB_ASSETS"       # 在代码里可以通过 env.EN_VERB_ASSETS 访问这些文件

# 数据库配置 (保持不变)
[[d1_databases]]
binding = "DB"
database_name = "verb-db"
database_id = "2b903f68-a865-46c5-934b-66b372ac868a" 

[vars]
# ADMIN_PASSWORD = "123"             # 管理员密码
MOBILE_PAGE_SIZE = 3                # 手机默认显示条数
MOBILE_OPTIONS = [3, 5, 10]         # 手机可选条数
PC_PAGE_SIZE = 10                   # PC 默认显示条数
PC_OPTIONS = [5, 10, 20, 50, 100]   # PC 可选条数
BATCH_SIZE = 500                    # 批量处理数据大小
#DEBOUNCE_MS = 300                   # 搜索请求的防抖延迟 (毫秒)